version: '3.5'
services:
  api-node:
    build: .
    restart: always
    ports:
      - '3000'
  
  nginx:
    build: ./nginx
    depends_on: 
      - api-node
    ports:
      - 8080:80
    container_name: nginx